name: craiglist_crawler
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - feedparser
  - lxml
  - matplotlib
  - numpy
  - pandas
  - jupyterlab
  - pip
  - requests
  - google-cloud-bigquery
  - pip:
    - python-dotenv
